language: python
addons:
  apt:
    packages:
    - hunspell
python:
- '3.5'
install:
- pip install Nikola[extras]
- git config --global user.name "Travis CI"
- git config --global user.email "jeffrey.arnold@gmail.com"
before_script:
- npm install markdown-spellcheck
- PATH="node_modules/.bin:$PATH"
script:
- make -C docs deploy  
- make -C slides deploy
- make -C lessons deploy
- ./gen-diffs.sh
- ./travis-deploy.sh
after_success:
- ./check-links.sh
- ./spell-check.sh
notifications:
  email:
    recipients:
    - jrnold@uw.edu
    - acasas2@uw.edu
    on_success: change
    on_failure: always
branches:
- master
env:
  global:
  - GH_REF: UW-POLS501/pols_501_wi16.git
  - secure: uzpq8SNvMA9tkE9FSwPKrnKffpylIEPi+dXai3Zfgw2ogogkpToijyOdAOR+Zzxj98vs8TjeY5YEOszB/THOpsVj3YfkrJ0kr1jKrxgdbOwGkH2sk6VDTjvF4ca2oEM+BZN7vPE4Ze0Ldsex2GztpLeEl1vJow7xZUu6N1t5Hs3pKtoby/LHY8pFOC1ztiZ9M6MaQBZ8+X9Uk7DDdsSNm5UaxG/ky2yZ/iT9B4NyUVDh6q5tNrT3XqX3LR9db46LwT3jDnusJiyWtPXUqIOrkOUpoL/6NnlE+J0ulV+ChC0X0gB2XGHmfirepV7R4N08xvXRf0EFMVHq94RksbAooArznQrQrNMro3uS9ZAJ1XpQmIZWhY9DHwlpsjyYr3tkHiSsCLsswEgZRJAGHMF/nNldaDHp4pKDd9fk/oT1RRYH7N3AuxBcoEP1Xk1izb1Da2qwJ1OGrACFL8lMfDYafXEjIxQFze4vW8J8oAiO+UWIo7R7ryu7ondE0YJRKyyio9A8epHeL0Xz6HhRR5bvtGQFGp7msPSEtC4Hm7ZzAmkt00ndGbUUJovt3AHKy7eNiSE0rBsVmYUwtYj1FlaREnu04p/qmMS/l1gvJohGYQ9+mj3oMBDEVt+XLk9lwT5ZgizCaP+lcOROnMjAKOk7B6QnTfB2vKwTm65VpgE6i8Q=
