language: python
addons:
  apt:
    packages:
    - libxml2-dev
python:
- '3.5'
install:
- pip install Nikola[extras]
script:
- git config user.name "Travis CI"
- git config user.email "jeffrey.arnold@gmail.com"
- git remote rm origin
- git remote add origin https://${GH_TOKEN}@github.com/UW-POLS501/pols_501_wi16.git
- git fetch origin
- cd web && nikola github_deploy | sed -e "s/[^\/]+@github.com/XXXX@github.com/g"
branches:
- master
env:
  global:
  - secure: ve8Ghg3CrceqEDNwUV9uHV+cDofB+8KON0ls2sShZkr403Xeil/kLzjapzRWtlnh18ooXL40JWLLJ1xctETlT+hxoyJNQbBI7+FypPS62az4jKPaO9BfCGdAxU2bRgt0xOwnHYDCbCnbkS/z3aCnEAAABoyQTZX6HGrgLVirosjis5v/j/qWNyznMQvpU6huasG0JhzjwzrJQYRxST9HbcJhQTY8l/Z6eQ3LMTf2HRKHVcMAf0NT5lFH+2xZ/gocOIYvKNorEiTmvXmDhjyTCDrIWHu/aIOQVWa0kFvFsALGp4PXvUdnbjKBYNaK0eyujeVhZ7R7XcN6qwwG3pm0KQbWshHMSoxGyyZ0isMXrRW9K0X1RwSZ7n5iEToJBa3GPNAkNGS4G6D+CdzQbYcKEbcxJ76SeCkF4y5ZE13LOn9iyZ5dWzrOdmMg53U8ssJbVoI263bbyJaUwQt7SFDwBthfYdIOVjO9uWMayM2LjcvZkEaUoPfcHOfBhDXRTNkcpTcKlWocCqwgOA/bWxTATbT/YXZr29q9VOKq4Z2pxydkAT+DFnD4QNuYEmnRNQKDuFo8duVN8qawIvd7OVemI/deib3R7rJ7itsAYch4WET5NqoRmuu0xA+ZJ0bIUZfTrfvrNZaWcGMs1+9+k1O7jiYrYyBYsXx9pv1GLUgtyNw=
