<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="author" content="Andreu Casas" />


<title>Interpreting linear regression outputs</title>

<script src="libs/jquery-1.11.0/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.1/css/cerulean.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.1/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.1/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.1/shim/respond.min.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="libs/highlight/textmate.css"
      type="text/css" />
<script src="libs/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img { 
  max-width:100%; 
  height: auto; 
}
</style>
<div class="container-fluid main-container">

<p>
<strong>POL S/CS&amp;SS 501, University of Washington, Winter 2016</strong>
</p>

$$
\DeclareMathOperator{\mean}{mean}
\DeclareMathOperator{\var}{var}
\DeclareMathOperator{\E}{E}
\DeclareMathOperator{\MSE}{MSE}
\DeclareMathOperator{\Bias}{Bias}
\DeclareMathOperator{\SE}{se}
\DeclareMathOperator{\SD}{sd}
\DeclareMathOperator{\argmin}{argmin}
\DeclareMathOperator{\argmax}{argmax}
$$

<div id="header">
<h1 class="title">Interpreting linear regression outputs</h1>
<h4 class="author"><em>Andreu Casas</em></h4>
<h4 class="date"><em>March 4, 2016</em></h4>
</div>


<div id="objective" class="section level3">
<h3>Objective</h3>
<p>What do the coefficients of linear regressions mean? Or the standard errors and p-values? How can we use them to make predictions? How can we compare the coefficients for different covariates? How can we present linear regression results in papers?</p>
</div>
<div id="introduction" class="section level3">
<h3>Introduction</h3>
<p>In this lab we’ll use the <code>Prestige</code> dataset we already used in the previous lab. Since some of you were having some issues downloading the <code>car</code> package, we decided to include the dataset in the package for this course (<code>uwpols501</code>). Use the <code>install_github()</code> function from the <code>devtools</code> package to update the package. Load also the rest of the packages that we’ll use in this lab.</p>
<pre class="r"><code>library(devtools)
install_github(username = &quot;jrnold&quot;, repo = &quot;UW-POLS501/r-uwpols501&quot;)</code></pre>
<pre class="r"><code>library(uwpols501)
data(&quot;Prestige&quot;)
library(broom)
library(dplyr)
library(coefplot)</code></pre>
</div>
<div id="fitting-a-linear-regression" class="section level3">
<h3>Fitting a linear regression</h3>
<p>Let’s begin by fitting a linear model with <code>prestige</code> as dependent variable and <code>education</code>, <code>income</code>, and <code>women</code> as covariates; and pull the coefficients table from the regression output using the <code>tidy()</code> function of the <code>broom</code> package.</p>
<pre class="r"><code>reg &lt;- lm(prestige ~ education + income + women, data = Prestige)
reg_table &lt;- tidy(reg)
reg_table</code></pre>
<pre><code>##          term     estimate    std.error  statistic      p.value
## 1 (Intercept) -6.794334203 3.2390886463 -2.0976067 3.851306e-02
## 2   education  4.186637275 0.3887012613 10.7708353 2.590069e-18
## 3      income  0.001313560 0.0002777812  4.7287593 7.579372e-06
## 4       women -0.008905157 0.0304070576 -0.2928648 7.702447e-01</code></pre>
<div id="challenge-1" class="panel panel-primary">
<div class="panel-heading">
<h3 class="panel-title">
Challenge
</h3>
</div>
<div class="panel-body">
<p>What’s the meaning of all the variables in the regression table?</p>
</div>
</div>
<div class="panel panel-info">
<div class="panel-heading">
<h3 class="panel-title">
<a data-toggle="collapse" href="#solution-1">Solution</a>
</h3>
</div>
<div id="solution-1" class="panel-collapse collapse">
<ul>
<li><code>term</code>: the name of the covariates (also known as independent-control variables, explanatory variables, predictors, etc.).</li>
<li><code>estimate</code>: the coefficient for each covariate. The average effect (rate of change) that a unit change of that covariate has on the dependent variable. The effect (coefficients) is in the units of the dependent variable.</li>
<li><code>std.error</code>: the standard error is the standard deviation of the coefficient. In other words, it describes the uncertainty associated with the estimate. We use the standard errors to compute Confidence Intervals for the coefficients: <span class="math inline">\(coef \pm t_{df} SE_{coef}\)</span>. The critical value <span class="math inline">\(t_{df}\)</span> depends on the desired confidence level and the degrees of freedom of the model: usually 1.96 (or 2).</li>
<li><code>statistic</code>: t-test statistic. How far away (how many standard deviations away) from the null value the coefficient is. <span class="math inline">\(T = \dfrac{coefficient - null value}{SE}\)</span>. Since in this case the null value is 0 and the standard deviation of the coefficient is the standard error, we obtain the t-statistic by calculating: <span class="math inline">\(T = \dfrac{coefficient}{SE}\)</span>.</li>
<li><code>p.value</code>: the probabilty of observing a coefficient if the null hypothesis were true.</li>
</ul>
</div>
</div>
</div>
<div id="interpreting-regression-tables" class="section level3">
<h3>Interpreting regression tables</h3>
<p>Let’s focus on the regression output for the covariate <code>education</code>.</p>
<pre class="r"><code>edu_reg &lt;- filter(reg_table, term == &#39;education&#39;)
edu_reg</code></pre>
<pre><code>##        term estimate std.error statistic      p.value
## 1 education 4.186637 0.3887013  10.77084 2.590069e-18</code></pre>
<div id="challenge-2" class="panel panel-primary">
<div class="panel-heading">
<h3 class="panel-title">
Challenge
</h3>
</div>
<div class="panel-body">
<p>In which units are the independent variable <code>prestige</code> and the covariate <code>education</code> represented? What’s their range?</p>
</div>
</div>
<p>The outcome variable <code>prestige</code> is measured using the Pineo-Porter prestige score for occupation, with range {14.80 , 87.20}. The independent variable <code>education</code> is measured in years (average years of education), with range {6.3 , 15.9}. The regression coefficient for <code>education</code> is <strong>4.18</strong> and the coefficient SE is <strong>0.39</strong>.</p>
<p>This means that, when <code>education</code> increases by 1 unit (so when the average education of people with certain occupation increase 1 year), <code>prestige</code> increases 0.39 units (so the Pineo-Porter prestige scores increases +0.39). For example, let’s take a look at the first observation in the dataset Prestige to see more clearly how we should interpret this result.</p>
<pre class="r"><code>Prestige[1,]</code></pre>
<pre><code>##                    education income women prestige census type
## gov.administrators     13.11  12351 11.16     68.8   1113 prof</code></pre>
<p>The first occupation in the dataset Prestige is <code>gov.administrators</code>, with an average of 13.11 years of <code>education</code> and an average Pineo-Porter <code>prestige</code> score of 68.8. Using the <code>education</code> coefficient of the model, we should predict that if <code>gov.administrators</code> were to increase their average years of education by 1 year, the expected Pineo-porter score would increase by <strong>4.18</strong>. Let’s use the coefficients in the model to predict the <code>prestige</code> score for gov.administrators with an <code>education</code> value of 13.11 and 14.11, and then compare them.</p>
<pre class="r"><code>gov_admin1 &lt;- Prestige[1,]
gov_admin2 &lt;- Prestige[1,] %&gt;%
  mutate(education = education + 1)
newdata &lt;- bind_rows(gov_admin1, gov_admin2)
gov_admin_pred &lt;- predict(reg, newdata)
gov_admin_pred</code></pre>
<pre><code>##        1        2 
## 64.21688 68.40352</code></pre>
<pre class="r"><code>gov_admin_pred[1] - gov_admin_pred[2]</code></pre>
<pre><code>##         1 
## -4.186637</code></pre>
<p>We can calculate confidence intervals around those estimates using the standard error (<strong>0.39</strong>) of the coefficient (<strong>4.18</strong>).</p>
<p>The hard way:</p>
<pre class="r"><code>cf &lt;- edu_reg$estimate
coef_upr &lt;- cf + 1.96 * edu_reg$std.error
coef_lwr &lt;- cf - 1.96 * edu_reg$std.error
c(coef_lwr, cf, coef_upr)</code></pre>
<pre><code>## [1] 3.424783 4.186637 4.948492</code></pre>
<pre class="r"><code>c(gov_admin_pred[1] + coef_lwr, gov_admin_pred[1] + cf, gov_admin_pred[1] + coef_upr)</code></pre>
<pre><code>##        1        1        1 
## 67.64167 68.40352 69.16538</code></pre>
</div>
<div id="comparing-the-effect-of-all-the-covariates" class="section level3">
<h3>Comparing the effect of all the covariates</h3>
<p>These are not standardized. Look for an existing package to do so.</p>
<pre class="r"><code>coefplot(reg)</code></pre>
<p><img src="interpreting_linear_regressions_files/figure-html/unnamed-chunk-8-1.png" title="" alt="" width="672" /></p>
</div>

<hr>
<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://licensebuttons.net/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
R code is licensed under a <a href="https://www.r-project.org/Licenses/BSD_2_clause">BSD 2-clause</a> license.

</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
