name: pols_501_wi16
dependencies:
- anaconda-client=1.2.1=py35_0
- clyent=1.2.0=py35_0
- openssl=1.0.2d=0
- pip=7.1.2=py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pyyaml=3.11=py35_1
- readline=6.2=2
- requests=2.9.0=py35_0
- setuptools=19.1.1=py35_0
- six=1.10.0=py35_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - appnope==0.1.0
  - argh==0.26.1
  - blinker==1.4
  - cloudpickle==0.1.1
  - decorator==4.0.6
  - docutils==0.12
  - doit==0.29.0
  - ghp-import2==1.0.0
  - gnureadline==6.3.3
  - husl==4.0.3
  - ipykernel==4.2.1
  - ipython==4.0.1
  - ipython-genutils==0.1.0
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter-client==4.1.1
  - jupyter-core==4.0.6
  - logbook==0.12.3
  - lxml==3.5.0
  - macfsevents==0.7
  - mako==1.0.3
  - markdown==2.6.5
  - markupsafe==0.23
  - micawber==0.3.3
  - mistune==0.7.1
  - natsort==4.0.4
  - nbconvert==4.1.0
  - nbformat==4.0.1
  - nikola==7.7.4
  - notebook==4.0.6
  - path.py==8.1.2
  - pathtools==0.1.2
  - pexpect==4.0.1
  - phpserialize==1.3
  - pickleshare==0.5
  - pillow==3.0.0
  - ptyprocess==0.5
  - pygal==2.0.12
  - pygments==2.0.2
  - pyphen==0.9.2
  - pyrss2gen==1.1
  - pyzmq==15.1.0
  - simplegeneric==0.8.1
  - smartypants==1.8.6
  - terminado==0.5
  - tornado==4.3
  - traitlets==4.0.0
  - typogrify==2.0.7
  - unidecode==0.4.18
  - watchdog==0.8.3
  - webassets==0.11.1
  - ws4py==0.3.4
  - yapsy==1.11.223

